from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Scene:
    scene_id: str
    min_duration_ms: int
    narration: str
    captions: tuple[str, ...]
    required_dom_text: tuple[str, ...] = ()


SCENES = (
    Scene(
        "problem",
        12_000,
        "A column rename looks simple. But in analytics, one field can feed "
        "models, metrics, dashboards, and the teams making decisions from "
        "them. Change it without context, and the failure appears far "
        "downstream.",
        (
            "A column rename looks simple.",
            "One field can feed decisions far downstream.",
        ),
    ),
    Scene(
        "truth-boundary",
        15_000,
        "ChangeSafe turns DataHub context into a verified migration decision "
        "before anything is published. This hosted demonstration uses "
        "checksum-pinned recorded DataHub evidence, exercises the real "
        "application pipeline, and clearly states that production rows were "
        "not queried.",
        (
            "DataHub context before publication.",
            "Recorded evidence · Production rows not queried",
        ),
        ("Recorded DataHub schema", "Production rows not queried"),
    ),
    Scene(
        "schema-request",
        18_000,
        "We start from the allowlisted order_details schema. DataHub returns "
        "fifty-five concrete fields with their native types and nullability. "
        "We select cust_email, propose primary_email, and analyze the change.",
        ("55 schema fields", "cust_email → primary_email"),
        ("Current field", "Analyze change"),
    ),
    Scene(
        "lineage",
        27_000,
        "Persisted events show each real phase. ChangeSafe retrieves "
        "field-scoped metadata, traces upstream and downstream dependencies, "
        "and labels the precision of every relationship. Exact routes name "
        "both returned fields. Multi-hop and dataset-level evidence disclose "
        "what DataHub did not return instead of inventing a connection. For "
        "this field, six upstream and twenty-five downstream relationships "
        "show how widely one contract change can travel.",
        (
            "Field-scoped dependency evidence",
            "Exact routes stay exact",
            "Unknown mappings stay unknown",
        ),
        ("Recorded dependents", "25 downstream assets"),
    ),
    Scene(
        "impact",
        22_000,
        "The same evidence drives six impact classifications and a "
        "deterministic factor score, with every point traceable to the factor "
        "ledger. Then ChangeSafe creates a conservative phase-one migration: "
        "the governed model stays intact while a compatibility shim exposes "
        "the old and new contract together.",
        (
            "Six evidence-led impact areas",
            "Every score factor is traceable",
        ),
        ("Impact classification", "Critical technical risk"),
    ),
    Scene(
        "artifacts",
        24_000,
        "The result is seven reviewable files with exact hashes, rollback "
        "guidance, and an operation-specific compatibility test. Twelve "
        "blocking checks verify the request, metadata, SQL, YAML, output "
        "contract, paths, rollback, and manifest.",
        ("7 verified files", "12 / 12 blocking checks"),
        ("Generated artifacts", "12 / 12"),
    ),
    Scene(
        "multi-field",
        16_000,
        "This is not an email-only workflow. Selecting order_status rebuilds "
        "the evidence for removal. Selecting order_total rebuilds it for a "
        "type change. The chosen field and operation bind the assessment and "
        "every generated byte. Unknown fields and destination collisions are "
        "blocked before a run can start.",
        ("Not email-only", "Field + operation bind every result"),
    ),
    Scene(
        "approval",
        19_000,
        "Finally, ChangeSafe pauses for the accountable owner. In this "
        "competition-safe mode, approval creates a non-mutating receipt and a "
        "downloadable patch. Nothing is silently written.",
        ("Human approval required", "NOT WRITTEN — SNAPSHOT MODE"),
        ("Approve preview", "Preview ready", "Download patch"),
    ),
    Scene(
        "closing",
        9_000,
        "ChangeSafe makes schema change review evidence-bound, fail-closed, "
        "and human approved—using DataHub to keep every dependency in view.",
        ("Evidence-bound. Fail-closed. Human-approved.",),
    ),
)

TOTAL_VISUAL_MS = sum(scene.min_duration_ms for scene in SCENES)

FORBIDDEN_CLAIMS = (
    "judge-prepared",
    "production rows passed",
    "live warehouse passed",
    "temporary tunnel",
    "api token",
    "private key",
)


def narration_word_count() -> int:
    text = " ".join(scene.narration for scene in SCENES)
    return len(re.findall(r"[A-Za-z0-9]+(?:[-'][A-Za-z0-9]+)*", text))


def default_output_dir() -> Path:
    return Path.home() / "Videos" / "ChangeSafe Submission"


def validate_storyboard() -> list[str]:
    errors: list[str] = []
    scene_ids = [scene.scene_id for scene in SCENES]
    if len(scene_ids) != len(set(scene_ids)):
        errors.append("scene ids must be unique")
    if not 145_000 <= TOTAL_VISUAL_MS <= 175_000:
        errors.append("visual runtime must be between 145000 and 175000 ms")
    for scene in SCENES:
        if not scene.narration.strip():
            errors.append(f"{scene.scene_id}: narration is required")
        if any(len(caption) > 96 for caption in scene.captions):
            errors.append(f"{scene.scene_id}: caption exceeds 96 characters")
    combined = " ".join(scene.narration for scene in SCENES).casefold()
    for fragment in FORBIDDEN_CLAIMS:
        if fragment in combined:
            errors.append(f"forbidden claim: {fragment}")
    return errors
