import { vi } from "vitest";

import type {
  ChangeSafeApi,
  PublicConfig,
  PublicationReceipt,
  RunEvent,
  RunView,
} from "../src/types";

const NOW = "2026-08-08T12:00:00Z";
export const RUN_ID = "0198f000-0000-7000-8000-000000000000";

const downstream = [
  ["revenue_by_customer", "Analytics", false],
  ["executive_customer_health", "Finance", true],
  ["churn_features", "Machine Learning", false],
  ["customer_360_export", "Customer Success", false],
] as const;

const artifactContents: Record<string, string> = {
  "models/marts/dim_customers.sql": `select
    customer_id,
    customer_email,
    customer_email as primary_email
from {{ ref('stg_customers') }}
`,
  "models/marts/dim_customers.yml": "version: 2\nmodels:\n  - name: dim_customers\n",
  "tests/assert_customer_email_compatibility.sql":
    "select * from dim_customers where customer_email is distinct from primary_email\n",
  "migrations/2026-08-06-customer-email-rename.md":
    "# Customer email migration\n",
  "ROLLBACK.md": "# Rollback\nRestore both model files.\n",
  "PR_BODY.md": "# Safe customer email rename\n<img src=x onerror=alert('unsafe')>\n",
  "changesafe-manifest.json": '{"files":{}}\n',
};

const files = Object.fromEntries(
  Object.entries(artifactContents).map(([path, content]) => [
    path,
    { path, content, sha256: "a".repeat(64) },
  ]),
);

export const goldenRun: RunView = {
  run_id: RUN_ID,
  state: "awaiting_approval",
  request: {
    asset_urn:
      "urn:li:dataset:(urn:li:dataPlatform:dbt,analytics.dim_customers,PROD)",
    operation: "rename",
    field: "customer_email",
    new_field: "primary_email",
    old_type: "STRING",
    new_type: "STRING",
    source_commit: "demo-unsafe-change",
    requested_by: "demo-user",
  },
  analysis: {
    context: {
      target_urn:
        "urn:li:dataset:(urn:li:dataPlatform:dbt,analytics.dim_customers,PROD)",
      target_name: "dim_customers",
      target_domain: "Analytics",
      field: "customer_email",
      field_type: "STRING",
      upstream_assets: [],
      downstream_assets: downstream.map(([name, domain, executive], index) => ({
        urn: `urn:li:dataset:downstream-${index}`,
        name,
        entity_type: index === 1 ? "dashboard" : "dataset",
        domain,
        field: "customer_email",
        is_executive: executive,
        is_production_ml: name === "churn_features",
        lineage_path: ["dim_customers", name],
      })),
      owners: [
        {
          urn: "urn:li:corpuser:data-platform",
          name: "Data Platform",
          ownership_type: "DATA_OWNER",
        },
      ],
      field_tags: ["PII"],
      glossary_terms: ["Customer email"],
      structured_properties: {},
      usage_tier: "high",
      queries: [],
      evidence: [],
      tool_evidence: [],
      provenance: {
        mode: "snapshot",
        retrieved_at: NOW,
        adapter_version: "replay-v1",
        snapshot_hash: "b".repeat(64),
      },
    },
    risk: {
      score: 90,
      band: "critical",
      recommended_strategy: "two_phase_compatibility_migration",
      factors: [
        ["base_rename", "Column rename", 25],
        ["downstream_assets", "4 downstream assets", 20],
        ["executive_downstream", "Executive report downstream", 15],
        ["governed_field", "Governed or PII field", 10],
        ["high_usage", "High query usage", 10],
        ["cross_domain", "Cross-domain impact", 10],
      ].map(([code, label, points]) => ({
        code: String(code),
        label: String(label),
        points: Number(points),
        evidence_urns: ["urn:li:evidence"],
      })),
    },
    artifacts: { files, manifest_hash: "c".repeat(64) },
    validation: {
      passed: true,
      checks: Array.from({ length: 10 }, (_, index) => ({
        code: `check_${index + 1}`,
        label: `Safety check ${index + 1}`,
        passed: true,
        blocking: true,
        detail: "Passed against generated bytes.",
      })),
    },
    publication_eligible: true,
  },
  publication: null,
  error: null,
  created_at: NOW,
  updated_at: NOW,
};

export const previewReceipt: PublicationReceipt = {
  mode: "preview",
  idempotency_key: "d".repeat(64),
  artifact_hash: "c".repeat(64),
  branch: null,
  pull_request_url: null,
  patch: "diff --git a/model.sql b/model.sql\n",
  writeback: {
    mode: "preview",
    label: "NOT WRITTEN — SNAPSHOT MODE",
    document_urn: null,
    updated_urns: [goldenRun.request.asset_urn],
    mutations: [],
    idempotent_reuse: false,
  },
};

const stateSequence = [
  "created",
  "loading_context",
  "scoring_risk",
  "generating",
  "validating",
  "awaiting_approval",
] as const;

const events: RunEvent[] = stateSequence.map((state, index) => ({
  run_id: RUN_ID,
  sequence: index + 1,
  state,
  public_message: state.replaceAll("_", " "),
  evidence: [],
  created_at: NOW,
}));

export function createGoldenApi(): ChangeSafeApi {
  let current: RunView = {
    ...goldenRun,
    state: "created",
    analysis: null,
  };
  const publicConfig: PublicConfig = {
    mode: "replay",
    live_context_available: false,
    llm_available: false,
    github_publication_available: false,
    datahub_writeback_available: false,
    openai_model: "gpt-5.6-luna",
  };
  return {
    getPublicConfig: vi.fn(async () => publicConfig),
    createRun: vi.fn(async () => current),
    getRun: vi.fn(async () => current),
    approve: vi.fn(async () => {
      current = {
        ...goldenRun,
        state: "completed",
        publication: previewReceipt,
      };
      return previewReceipt;
    }),
    subscribe: (_runId, _afterSequence, onEvent) => {
      queueMicrotask(() => {
        for (const event of events) {
          if (event.state === "awaiting_approval") current = goldenRun;
          onEvent(event);
        }
      });
      return () => undefined;
    },
  };
}
