import { Check, Copy, FileCode2 } from "lucide-react";
import { useState } from "react";

import type { ArtifactBundle } from "../types";

const PREFERRED_PATH = "models/marts/dim_customers.sql";

interface ArtifactExplorerProps {
  artifacts: ArtifactBundle;
}

function shortPath(path: string): string {
  return path.length > 44 ? `…/${path.split("/").slice(-2).join("/")}` : path;
}

export function ArtifactExplorer({ artifacts }: ArtifactExplorerProps) {
  const paths = Object.keys(artifacts.files);
  const initial = paths.includes(PREFERRED_PATH) ? PREFERRED_PATH : paths[0];
  const [selected, setSelected] = useState(initial);
  const [copied, setCopied] = useState(false);

  const file = selected ? artifacts.files[selected] : undefined;
  const copy = async () => {
    if (!file || !navigator.clipboard) return;
    await navigator.clipboard.writeText(file.content);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1200);
  };

  return (
    <section className="artifact-explorer" id="artifacts" aria-labelledby="files-heading">
      <nav className="file-rail" aria-label="Generated files">
        <h2 id="files-heading">Generated artifacts</h2>
        <span className="file-count">{paths.length} verified files</span>
        <div role="tablist" aria-orientation="vertical">
          {paths.map((path) => (
            <button
              aria-controls="artifact-code"
              aria-selected={selected === path}
              className={selected === path ? "is-selected" : ""}
              data-testid="artifact-file"
              key={path}
              onClick={() => setSelected(path)}
              role="tab"
              title={path}
              type="button"
            >
              <FileCode2 aria-hidden="true" />
              <span>{shortPath(path)}</span>
            </button>
          ))}
        </div>
      </nav>
      <div className="code-inspector">
        <header>
          <strong>{selected}</strong>
          <span>Exact generated bytes</span>
          <button aria-label="Copy selected artifact" onClick={copy} type="button">
            {copied ? <Check aria-hidden="true" /> : <Copy aria-hidden="true" />}
          </button>
        </header>
        <pre className="artifact-code" id="artifact-code" role="tabpanel">
          <code>{file?.content ?? "No artifact selected."}</code>
        </pre>
        <footer>
          <span>SHA-256</span>
          <code>{file?.sha256 ?? "Unavailable"}</code>
        </footer>
      </div>
    </section>
  );
}
